### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by fbartels** [duesee/imap-sec#4]
Hi,

trying to run the command from the readme leads to a compilation error:

```
$ cargo run -- --help
    Updating git repository `https://github.com/duesee/imap-flow`
error: failed to get `imap-flow` as a dependency of package `imap-sec v0.1.0 (xx/imap-sec)`

Caused by:
  failed to load source for dependency `imap-flow`

Caused by:
  Unable to update https://github.com/duesee/imap-flow?branch=feature_expose_stream#4b800619

Caused by:
  revspec '4b800619181aff5bfa7b64ac2077b48143633afc' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by duesee** [comment]
Grrrr... Thanks for reporting! We renamed `imap-flow` to `imap-next` a few days ago. I now updated `imap-sec` :-) Can you see if it works and then close this issue?

**Comment by fbartels** [comment]
Hi @duesee,

thanks for the quick feedback. I can confirm that when pulling the latest changes the project now builds.
